# version: "3.3"
# name: vimeo_scaleit
services:
  scaleit:
    container_name: scaleit
    build:
      context: ../
    entrypoint: [ "/bin/bash", "-c"]
    command: ./bin/scaleit-linux-amd64
    ports: ["8123:8123"]
  autoscaler:
    depends_on: [scaleit]
    container_name: autoscaler
    image: scaleit
    entrypoint: python
    command: app.py
    ports: ["8000:8000"] # help you observe prometheus log
    environment:
      -  APP_SERVICE_URL=http://scaleit
      -  APP_SERVICE_PORT=8123
      -  SCALE_RESOLUTION_TIME=5
      -  SCALE_METRIC=.80
      -  SCALE_TOLERANCE=.10
      -  LOG_LEVEL=DEBUG
